project:
  type: book

book:
  title: "Criticality in Deep Neural Networks"
  subtitle: "Master thesis"
  author: "Marc Steiner"
  date: last-modified
  sidebar:
    search: true
  repo-url: https://github.com/astroviking/master-thesis/
  repo-actions: [edit]
  downloads: [pdf]
  sharing: [twitter, facebook]
  chapters:
    - index.qmd
    - chapters/abstract.qmd
    - chapters/intro.qmd
    - chapters/summary.qmd
    - chapters/references.qmd

bibliography: bibliography/references.bib

format:
  html:
    title-block-banner: resources/images/banner-background.webp
    highlight-style: github
    code-fold: true
    code-tools:
      source: repo
    code-overflow: wrap
    code-link: true
    code-line-numbers: true
    theme:
      dark: [darkly, resources/css/theme-dark.scss]
      light: [flatly, resources/css/theme-light.scss]
    link-external-icon: true
    link-external-newwindow: true
    comments:
      hypothesis: true

  pdf:
    documentclass: mimosis
    mainfont: "Source Sans Pro"
    monofont: "JetBrains Mono"

    highlight-style: github
    toc: true
    #lot: true
    #lof: true
    number-sections: true
    colorlinks: true

editor: visual



