project:
  type: book

book:
  title: "Master thesis"
  author: "Marc Steiner"
  date: "11/20/2022"
  sidebar:
    search: true
    style: docked
  repo-url: https://github.com/astroviking/master-thesis/
  repo-actions: [edit]
  downloads: [pdf, epub]
  sharing: [twitter, facebook]
  chapters:
    - index.qmd
    - chapters/abstract.qmd
    - chapters/intro.qmd
    - chapters/summary.qmd
    - chapters/references.qmd

bibliography: bibliography/references.bib

format:
  html:
    highlight-style: github
    code-fold: true
    code-tools:
      source: repo
    code-overflow: wrap
    code-link: true
    code-line-numbers: true
    theme:
      dark: darkly
      light: flatly
    link-external-icon: true
    link-external-newwindow: true
    comments:
      hypothesis:
        theme: clean

  pdf:
    documentclass: scrreprt
    highlight-style: github
    toc: true
    number-sections: true
    colorlinks: true

editor: visual



