project:
  type: book
  pre-render: scripts/install_mt2prolite.py

book:
  title: "Criticality in Deep Neural Networks"
  subtitle: "Master thesis"
  date: last-modified
  author:
    - name: "Marc Steiner"
      url: astroviking.github.io/master-thesis
      affiliation: Institute of Neuroinformatics, University of Zurich / ETH Zurich
      affiliation-url: https://www.ini.uzh.ch
  repo-url: https://github.com/astroviking/master-thesis/
  repo-actions: [edit]
  downloads: [pdf]
  sharing: [twitter, facebook, linkedin]
  reader-mode: true
  
  chapters:
    - index.qmd
    - chapters/abstract.qmd
    - chapters/intro.qmd
    - chapters/summary.qmd
    - chapters/references.qmd

bibliography: bibliography/references.bib

format:
  html:
    monofont: "JetBrains Mono"
    title-block-banner: resources/images/banner-background.webp
    highlight-style: github
    code-fold: true
    code-tools:
      source: repo
    code-overflow: scroll
    code-link: true
    code-line-numbers: true
    theme:
      dark: [darkly, resources/css/theme-dark.scss, resources/scss/JetBrainsMono.scss]
      light: [flatly, resources/css/theme-light.scss, resources/scss/JetBrainsMono.scss]
    resource-path: 
      - resources/fonts/JetBrainsMono
    link-external-newwindow: true
    comments:
      hypothesis: true
    filters:
      - lightbox
    lightbox: auto

  pdf:
    # Uses MathTime Professional 2 Fonts, comment out if not installed
    template: resources/latex-template/template.tex
    latex-input-paths: 
      - "resources/latex-template/"
    documentclass: mimosis
    mainfont: "STIX Two Text"
    monofont: "JetBrains Mono"
    highlight-style: github
    toc: true
    #lot: true
    #lof: true
    number-sections: true
    colorlinks: true

editor: visual



